const mobiliario = {
    info: {
        productos: 40,
    },
    results: [
        {
            id: 1,
            nombre: "Almacenamiento de Aula",
            categoria: "Escolar",
            precio: "$1.500.000",
            color: "Beige",
            medida: "50x40cm",
            peso: "50kg",
            descripcion: "Diseñado específicamente para mantener los útiles escolares organizados y seguros. Este robusto armario de metal con puertas y llave es la solución perfecta para las necesidades de almacenamiento en salones de clase.",
            image: "https://jordansas.com/wp-content/uploads/2024/07/1-2-Almacenamiento-de-aula-600x600.jpg",
        },
        {
            id: 2,
            nombre: "Acrchivador 2x1 Metalico",
            categoria: "Administrativo",
            precio: "$1.552.000",
            color: "Makadamia",
            medida: "70x50cm",
            peso: "60kg",
            descripcion: "Descubre nuestro elegante y funcional archivador 2×1, una combinación perfecta de metal y madera diseñado para satisfacer todas tus necesidades de almacenamiento y organización. ",
            image: "https://jordansas.com/wp-content/uploads/2024/07/2-2-archivador-2x1-1-600x600.jpg",
        },
        {
            id: 3,
            nombre: "Archivador Metalico 2x1 con jaladera lateral mini",
            categoria: "Administrativo",
            precio: "$2.250.000",
            color: "Blanco",
            medida: "123x80cm",
            peso: "80kg",
            descripcion: "Organiza tu espacio de manera eficiente con nuestro Archivador Metálico 2×1 con Jaladera Lateral Mini. Este elegante y compacto archivador es ideal para oficinas, estudios y cualquier lugar donde se requiera un almacenamiento práctico y seguro.",
            image: "https://jordansas.com/wp-content/uploads/2024/07/3-1-mueble-2x1-aula.jpg",
        },
        {
            id: 4,
            nombre: "Base Comedor Hug",
            categoria: "Comedor",
            precio: "$3.000.000",
            color: "Cristal",
            medida: "70x50",
            peso: "96kg",
            descripcion: "Base para comedor en madera de nogal. Añade calidez y elige entre superficies de madera o vidrio. Dimensiones personalizables.",
            image: "https://jordansas.com/wp-content/uploads/2024/08/COMEDOR-MADERA-VIDRIO-4-PUESTOS-SAM-600x600.jpg",
        },
        {
            id: 5,
            nombre: "Biblioteca Niños",
            categoria: "Sala",
            precio: "$3.800.000",
            color: "Blanco",
            medida: "210x102cm",
            peso: "105kg",
            descripcion: "Biblioteca infantil de madera de pino, ideal para organizar libros en espacios pequeños. Acabado en poliuretano blanco.",
            image: "https://jordansas.com/wp-content/uploads/2024/08/BIBLIOTECA-NINOS-SAM-1-scaled.jpg",
        },
        {
            id: 6,
            nombre: "Mesa Harmony Nogal",
            categoria: "Comedor",
            precio: "$7.000.000",
            color: "Makadamia",
            medida: "180x90cm",
            peso: "85kg",
            descripcion: "Impresione a sus invitados con la mesa de comedor Harmony oscuro negro 180x90. Con su encimera rectangular de madera de acacia y patas de acero, esta mesa es tanto elegante como duradera. ",
            image: "https://cdn.wonderstatic.com/product-image/stol-harmony-walnut-180x90-cm-akacja-nogi-czarne-2.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 7,
            nombre: "Mesa South Beach",
            categoria: "Comedor",
            precio: "$5.000.000",
            color: "Gris",
            medida: "180x90cm",
            peso: "82kg",
            descripcion: "Esta elegante mesa de comedor South Beach de 180x90 es una pieza de diseño moderno y minimalista que añade un toque de elegancia a cualquier espacio. El tablero de vidrio y madera da un efecto de mármol blanco, que parece flotar sobre las robustas patas de acero recubiertas de polvo.",
            image: "https://cdn.wonderstatic.com/product-image/stol-south-beach-180x90-cm-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 8,
            nombre: "Mesa Cesaro",
            categoria: "Sala",
            precio: "$10.000.000",
            color: "Abedul",
            medida: "200x100cm",
            peso: "60kg",
            descripcion: "La mesa de comedor Cesaro, diseñada por Andreas Weber, es una pieza de estilo moderno que combina acero dorado y fresno macizo, dando lugar a un mueble contemporáneo muy atractivo.",
            image: "https://cdn.wonderstatic.com/product-image/stol-cesaro-200x100-cm-naturalny-nogi-zlote-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 9,
            nombre: "Mesa Puro Plain",
            categoria: "Sala",
            precio: "$7.000.000",
            color: "Abedul",
            medida: "50x70cm",
            peso: "30kg",
            descripcion: "La 'Mesa Puro Plain 160x80cm' es una mesa de comedor única en su tipo con su diseño rectangular y su acabado en colores de madera. Hecha de madera lacada de mango, esta mesa es tan funcional como elegante.",
            image: "https://cdn.wonderstatic.com/product-image/stol-puro-plain-z-szufladami-160x80cm-naturalny-1?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 10,
            nombre: "Mesa Bora Bora",
            categoria: "Sala",
            precio: "$1.300.000",
            color: "Negra",
            medida: "80x80cm",
            peso: "50kg",
            descripcion: "Hermosa mesa para que puede caer bien a cualquier estilo de sala, ya que su conformidad y color lo permiten.",
            image: "https://cdn.wonderstatic.com/product-image/stol-ogrodowy-bora-bora-80x80-cm-czarny-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 11,
            nombre: "Mesa Brooklyn Nature",
            categoria: "Sala",
            precio: "$6.300.000",
            color: "Madera",
            medida: "80x160cm",
            peso: "30kg",
            descripcion: "La mesa de comedor Brooklyn Nature de 160x80cm es una fusión perfecta de modernismo y elegancia. Fabricada de madera sheesham de color marrón, su encimera rectangular con acabado lacado aporta un tono cálido y tranquilo a su sala de estar.",
            image: "https://cdn.wonderstatic.com/product-image/stol-brooklyn-160x80-cm-sheesham-ciemnobrazowy-1?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 12,
            nombre: "Silla Reposabrazos Costa",
            categoria: "Sala",
            precio: "2.500.000",
            color: "Negro",
            medida: "52x70.5cm",
            peso: "7.4kg",
            descripcion: "El respaldo de esta silla, con su espalda envolvente, ofrece un increíble confort. Está fabricado con madera de álamo barnizada en color nogal y el asiento es de polipiel negra.",
            image: "https://cdn.wonderstatic.com/product-image/krzeslo-z-podlokietnikami-costa-52x71-cm-czarne-ekoskora-4.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 13,
            nombre: "Mesa polar latón",
            categoria: "Sala",
            precio: "2.000.000",
            color: "Mate",
            medida: "80x60cm",
            peso: "44.5kg",
            descripcion: "Un escritorio de diseño con formas elegantes y sobrias que llaman la atención. Sus tableros de cristal colocados sobre patas de acero ofrecen una apariencia de ligereza y sencillez para un espacio de trabajo agradable y confortable.",
            image: "https://cdn.wonderstatic.com/product-image/biurko-polar-135x65-cm-szklo-hartowane-nogi-zlote-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 14,
            nombre: "Silla Butterfly",
            categoria: "Sala",
            precio: "3.2000.000",
            color: "Marron",
            medida: "80x87cm",
            peso: "6.2kg",
            descripcion: "Este sillón vintage combina una estructura de acero con un acabado de cobre y un asiento de piel de vaca patinada para dar un aspecto cálido. Así, el sillón Mariposa se basa en la combinación de lo original y lo clásico desde 1938.",
            image: "https://cdn.wonderstatic.com/product-image/fotel-butterfly-brazowy-80x87cm-skora-naturalna-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 15,
            nombre: "Mesilla Luxury",
            categoria: "Habitacion",
            precio: "8.0000.000",
            color: "gris",
            medida: "49x50cm",
            peso: "17.58kg",
            descripcion: "Esta mesillamoderna y sofisticada está compuesta por una estructura de madera comprimida lacada en negro y paneles de espejo. Su silueta minimalista está resaltada por unas asas de cristal que evocan los diamantes y contrastan con sus ángulos rectos.",
            image: "https://cdn.wonderstatic.com/product-image/szafka-nocna-luxury-push-49x50-cm-szara-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 16,
            nombre: "Mesa Office Symphony",
            categoria: "Administrativo",
            precio: "13.8000.000",
            color: "Madera",
            medida: "160x70cm",
            peso: "64.5kg",
            descripcion: "Esta mesa nos permite tener un entorno administrativo sin necesidad de salir de nuestro hogar, esta 100% equipada para las necesidades laborales.",
            image: "https://cdn.wonderstatic.com/product-image/biurko-symphony-160x80-cm-drewniane-2.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 17,
            nombre: "Silla Oficina Giratoria Dottore",
            categoria: "Administrativo",
            precio: "3.3000.000",
            color: "Blanco",
            medida: "57x105cm",
            peso: "12.5kg",
            descripcion: "Esta silla de oficina ajustable es un clásico con sus ángulos rectos y su color polivalente. Te dará un ambiente serio para trabajar.",
            image: "https://cdn.wonderstatic.com/product-image/krzeslo-biurowe-dottore-44x78-cm-szare-1.jpeg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 18,
            nombre: "Silla Oficina Giratoria",
            categoria: "Administrativo",
            precio: "2.3000.000",
            color: "Beige",
            medida: "57x105cm",
            peso: "12.5kg",
            descripcion: "Esta silla de oficina ajustable es un clásico con sus ángulos rectos y su color polivalente. Te dará un ambiente serio para trabajar.",
            image: "https://cdn.wonderstatic.com/product-image/krzeslo-biurowe-dottore-60x81-cm-brazowe-12.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 19,
            nombre: "Estanteria Loft",
            categoria: "Administrativo",
            precio: "4.8000.000",
            color: "Oro",
            medida: "115x195cm",
            peso: "41.3kg",
            descripcion: "Los estantes abiertos son compañeros de decoración ideales ayudan a mantener las cosas ordenadas, lucen ligeras y gracias al gran espacio de almacenamiento en los estantes, ofrecen mucho espacio para decoraciones, cajas, cestas o jarrones o en el estilo clásico, para libros.",
            image: "https://cdn.wonderstatic.com/product-image/regal-authentico-zick-zack-100x180-cm-drewniany-1?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 20,
            nombre: "Sofa Cubetto 3 Puestos",
            categoria: "Sala",
            precio: "20.0000.000",
            color: "Crema",
            medida: "220x67cm",
            peso: "74kg",
            descripcion: "El sofá Cubetto 3 pl crema 220cm es un elemento imprescindible para cualquier hogar contemporáneo. Este sofá de estilo moderno y escandinavo, fabricado con madera de abeto y tapizado con material sintético de color beige, ofrece una combinación perfecta de comodidad y estilo.",
            image: "https://cdn.wonderstatic.com/product-image/sofa-cubetto-cord-3-os-220-cm-kremowa-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 21,
            nombre: "Exterior Sofa Set Holiday",
            categoria: "Sala",
            precio: "14.3000.000",
            color: "Gris",
            medida: "242x63cm",
            peso: "50kg",
            descripcion: "¿Qué podría ser más hermoso que mover la vida afuera en los primeros rayos del sol? Es aún mejor si todos pueden encontrar un lugar cómodo para sentarse o relajarse juntos, como en el grupo de asientos de la esquina navideña, que también viene con una mesa.",
            image: "https://cdn.wonderstatic.com/product-image/sofa-ogrodowa-ze-stolikiem-holiday-white-242x242-cm-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 22,
            nombre: "Cama Tivoli Crudo",
            categoria: "Habitacion",
            precio: "10.6000.000",
            color: "Crema",
            medida: "198x105cm",
            peso: "50kg",
            descripcion: "La colección Tivoli ofrece camas de tela en colores que son fáciles de integrar en su decoración. El cojín integrado en el cabecero le permite reclinarse cómodamente para leer o ver la televisión. Capacidad de carga máxima: 250 kg.",
            image: "https://cdn.wonderstatic.com/product-image/lozko-tivoli-160x200-cm-ecru-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 23,
            nombre: "Reloj Pared Like Umbrella",
            categoria: "Sala",
            precio: "5000.000",
            color: "Negro",
            medida: "105cm",
            peso: "0.7kg",
            descripcion: "Un clásico de nuestra colección. El Umbrella es perfecto para un bar, una sala de estar, un despacho o la cocina..... ¡este gran reloj llama la atención de inmediato! Los cuatro dígitos pueden montarse de forma flexible o dejarse fuera. Disponible en varios colores.",
            image: "https://cdn.wonderstatic.com/product-image/zegar-wiszacy-like-umbrella-o100-cm-czarny-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 24,
            nombre: "Cama de Madera Pura",
            categoria: "Habitacion",
            precio: "5000.000",
            color: "Madera",
            medida: "200x120cm",
            peso: "80kg",
            descripcion: "Una tradicional y comoda cama base te espera, este producto se describe como un ambiente familiar por sus amplias medidas y muy comodo.",
            image: "https://cdn.wonderstatic.com/product-image/lozko-puro-high-180x200-cm-mango-1.jpg?width=350&height=350&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 25,
            nombre: "Lampara de Pie Natural Straight",
            categoria: "Habitacion",
            precio: "5.0000.000",
            color: "Negro",
            medida: "52x171cm",
            peso: "13.74kg",
            descripcion: "La elegancia moderna se encuentra con la naturaleza virgen: esta lámpara estándar combina elementos naturales con un elegante estilo moderno de una manera encantadora. Reciclaje en su forma más natural. La madera flotante indonesia, moldeada por el mar, se recoge y se usa para crear piezas individuales.",
            image: "https://cdn.wonderstatic.com/product-image/lampa-podlogowa-nature-straight-52x171-cm-czarno-drewniana-1?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 26,
            nombre: "Sofa Esq Gianni",
            categoria: "Sala",
            precio: "15.6000.000",
            color: "Gris",
            medida: "290x88cm",
            peso: "110kg",
            descripcion: "La gama Gianni ofrece una amplia variedad de sofás de esquina en terciopelo o tela. Gris, verde, crema, marrón con patas cromadas, negro o acero bruto: puede encontrar el modelo que le convenga. También puede elegir entre una esquina derecha o izquierda.",
            image: "https://cdn.wonderstatic.com/product-image/naroznik-gianni-290x167-cm-szary-lewy-nogi-czarne-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 27,
            nombre: "Vasija Barfly",
            categoria: "Sala",
            precio: "3000.000",
            color: "Berry",
            medida: "20cm",
            peso: "1.2kg",
            descripcion: "Jarrón en rosa una serie de jarrones con algo de cierto. La serie Barfly juega con colores pastel suaves, formas versátiles y vidrio sólido con diferentes diseños. El vidrio de color y las formas inusuales de los jarrones recuerdan al vidrio artístico de Murano, mientras que el cuello del jarrón está decorado con un anillo de latón reluciente.",
            image: "https://cdn.wonderstatic.com/product-image/wazon-barfly-o17x20-cm-rozowy-1?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 28,
            nombre: "Espejo Bella",
            categoria: "Sala",
            precio: "1.0000.000",
            color: "Cristal",
            medida: "130x30cm",
            peso: "4.8kg",
            descripcion: "La colección Bella ofrece seis grandes espejos con marco de aluminio lacado en negro. Con su diseño minimalista, encajan perfectamente en un interior moderno",
            image: "https://cdn.wonderstatic.com/product-image/lustro-wiszace-bella-30x130-cm-czarne-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 29,
            nombre: "Espejo Pared Nastrp",
            categoria: "Sala",
            precio: "3.0000.000",
            color: "Negro",
            medida: "80x114cm",
            peso: "15kg",
            descripcion: "Este espejo de pared cuadrado se compone de varios espejos pequeños y forma un objeto de espejo único. Gracias a su diseño, el espejo es ideal como decoración de pared. Los espejos reflejan la luz, dando a la habitación más profundidad y luminosidad.",
            image: "https://cdn.wonderstatic.com/product-image/lustro-wiszace-odwracalne-rama-stalowa-czarna-80x114-cm-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 30,
            nombre: "Figura Decorativa Elefant Dumbo",
            categoria: "Sala",
            precio: "200.000",
            color: "Marron",
            medida: "18x19cm",
            peso: "0.38kg",
            descripcion: "¿Por qué son tan populares los elefantes? Quizás porque son un símbolo de sabiduría y cohesión familiar. Esta figura decorativa creativa de Kare enfatiza el tema de la familia con su representación humorística de un elefante bebé que monta un gran jumbo. ¿Quién podría resistir el encanto de la pareja de ellos?",
            image: "https://cdn.wonderstatic.com/product-image/figurka-dekoracyjna-elephant-dumbo-uno-18x19-cm-brazowa-1?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 31,
            nombre: "Mesa Plegable Balcony",
            categoria: "Administrativo",
            precio: "800.000",
            color: "Negro",
            medida: "70x60cm",
            peso: "3.2kg",
            descripcion: "Esta mesa redonda es justo con su tamaño y diámetro de 60 cm para todos los insertos en el balcón y la terraza. Dos personas encuentran espacio en él. El diseño moderno de la mesa hace que sus usos no sean ilimitados.",
            image: "https://cdn.wonderstatic.com/product-image/stol-ogrodowy-maly-w-kolorze-czarnym-aluminiowy-o60-cm-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 32,
            nombre: "Sofa 3 PL. Night Fever",
            categoria: "Sala",
            precio: "17.800.000",
            color: "Violeta",
            medida: "232x83cm",
            peso: "50kg",
            descripcion: "El sofá Night Fever 3 pl lila es una pieza de glamour de la categoría de Sofás. El color profundo de violeta en el asiento contrasta hermosamente con las patas de acero dorado. El material de tapicería es de tejido sintético, proporcionando un toque de elegancia y sofisticación.",
            image: "https://cdn.wonderstatic.com/product-image/sofa-night-fever-232-cm-fioletowa-1.jpg?width=850&height=650&quality=85&dpr=1.25&format=pjpg&auto=webp&fit=bounds&io=true",
        },
        {
            id: 33,
            nombre: "Silla Movie Universitaria",
            categoria: "Escolar",
            precio: "500.000",
            color: "Gris",
            medida: "20x30cm",
            peso: "2.3kg",
            descripcion: "Silla multipropósito que brinda versatilidad y confort. Su diseño además de ser ergonómico es de fácil almacenamiento. Ideal para todo tipo de espacios.",
            image: "https://muma.co/wp-content/uploads/2023/07/MOVIE-UNIVERSITARIA-FRONTAL.png",
        },
        {
            id: 34,
            nombre: "Escriotio Studio",
            categoria: "Escolar",
            precio: "700.000",
            color: "Abedul",
            medida: "63x23cm",
            peso: "16.2kg",
            descripcion: "Innovador escritorio diseñado para brindar la máxima comodidad y funcionalidad. Este mobiliario de calidad se adapta perfectamente a tus necesidades operativas, optimizando el uso del espacio.",
            image: "https://muma.co/wp-content/uploads/2023/04/op_ESCRITORIO-STUDIO-5.jpg",
        },
        {
            id: 35,
            nombre: "Puesto de Trabajo",
            categoria: "Administrativo",
            precio: "900.000",
            color: "Makadamia",
            medida: "63x18cm",
            peso: "45kg",
            descripcion: "Una estación de trabajo moderna, versátil y perfecta para tus necesidades operativas, optimizando tus espacios con estilo.",
            image: "https://muma.co/wp-content/uploads/2023/04/op_PUESTOS-DE-TRABAJO-KOU-BASIC-2.jpg",
        },
        {
            id: 36,
            nombre: "Mesa Soho",
            categoria: "Escolar",
            precio: "1.000.000",
            color: "Blanco",
            medida: "50x70cm",
            peso: "23kg",
            descripcion: "Mesas auxiliares con un diseño elegante y materiales duraderos. Su sistema de electrificación proporciona soluciones prácticas para las necesidades de los usuarios, haciendo que sean ideales para espacios de reunión y espera.",
            image: "https://muma.co/wp-content/uploads/2023/07/MESA-SOHO-BAJA.png",
        },
        {
            id: 37,
            nombre: "Puesto de Trabajo Cobal",
            categoria: "Administracion",
            precio: "1.300.000",
            color: "Abedul",
            medida: "63x18cm",
            peso: "32kg",
            descripcion: "Nuestra estación de trabajo moderna, una solución versátil y eficiente que se adapta perfectamente a tus necesidades operativas. Diseñada para optimizar tus espacios de trabajo con estilo y funcionalidad.",
            image: "https://muma.co/wp-content/uploads/2023/04/op_COBAL-3.jpg",
        },
        {
            id: 38,
            nombre: "Mesa Cafe Fix",
            categoria: "Administracion",
            precio: "1.040.000",
            color: "Makadamia",
            medida: "20x73cm",
            peso: "36kg",
            descripcion: "Las mesas de exterior están diseñadas para uso en espacios al aire libre, estas suelen estar fabricadas con materiales que pueden resistir ciertas condiciones,  pare no para condiciones climáticas extremas o para exposición directa a la intemperie.",
            image: "https://muma.co/wp-content/uploads/2023/07/MESA-CUADRADA-FIX-2.png",
        },
        {
            id: 39,
            nombre: "Puestos de Trabajo Epik Plus",
            categoria: "Administracion",
            precio: "1.540.000",
            color: "Abedul",
            medida: "63x18cm",
            peso: "35kg",
            descripcion: "Maximiza tu eficiencia con una estación de trabajo moderna, versátil y llena de estilo para tus necesidades operativas",
            image: "https://muma.co/wp-content/uploads/2023/04/op_EPIK-PLUS-2.jpg",
        },
        {
            id: 40,
            nombre: "Silla Interlocutora Mia",
            categoria: "Escolar",
            precio: "350.000",
            color: "Negra",
            medida: "20x50cm",
            peso: "1.5kg",
            descripcion: "Silla multipropósito y multifuncional, con diseño atractivo y divertido. La variedad en colores y versiones le permite adaptarse a diferentes ambientes.",
            image: "https://muma.co/wp-content/uploads/2023/04/op_63-SILLA-MIA-1.jpg",
        },
    ],
}
  
function renderizarProductos() {
    const container = document.getElementById("productos-container");

    mobiliario.results.forEach((producto) => {
        // Crear la tarjeta de producto
        const productCard = document.createElement("div");
        productCard.classList.add("product-card");

        // Contenido de la tarjeta (solo imagen, nombre y precio)
        productCard.innerHTML = `
            <img src="${producto.image}" alt="${producto.nombre}">
            <div class="product-card-content">
                <h3 class="product-name">${producto.nombre}</h3>
                <p class="product-price">${producto.precio}</p>
            </div>
        `;

        // Evento para mostrar el detalle del producto al hacer clic
        productCard.addEventListener("click", () => {
            mostrarDetalleProducto(producto);
        });

        container.appendChild(productCard);
    });
}

// Función para mostrar el detalle del producto en la sección aparte
function mostrarDetalleProducto(producto) {
    const detalleProducto = document.getElementById("detalle-producto");

    // Actualizar el contenido de detalle-producto
    detalleProducto.innerHTML = `
        <h2>${producto.nombre}</h2>
        <img src="${producto.image}" alt="${producto.nombre}">
        <p><strong>Precio:</strong> ${producto.precio}</p>
        <p><strong>Descripción:</strong> ${producto.descripcion}</p>
        <p><strong>Color:</strong> ${producto.color}</p>
        <p><strong>Medida:</strong> ${producto.medida}</p>
        <p><strong>Peso:</strong> ${producto.peso}</p>
    `;

    detalleProducto.classList.add("mostrar");
}

document.addEventListener("DOMContentLoaded", renderizarProductos);
