const mobiliario = {
    info: {
      count: 826,
      pages: 42,
      next: "https://rickandmortyapi.com/api/character?page=2",
      prev: null,
    },
    results: [
      {
        id: 1,
        nombre: "Almacenamiento de Aula",
        categoria: "Almacenamiento",
        tipo: "Escolar",
        precio: "$1.500.000",
        color: "Beige",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
      },
      {
        id: 2,
        nombre: "Ac¿rchivador 2x1 Metalico",
        categoria: "Almacenamiento",
        tipo: "Administrativo",
        precio: "$1.552.000",
        color: "Makadamia",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
      },
      {
        id: 3,
        nombre: "Ac¿rchivador Metalico 2x1 con jaladera lateral mini",
        categoria: "Almacenamiento",
        tipo: "Administrativo",
        precio: "$2.250.000",
        color: "Blanco",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 4,
        nombre: "Base Comedor Hug",
        categoria: "Comedor",
        tipo: "Mobiliario Hogar",
        precio: "$3.000.000",
        color: "Cristal",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 5,
        nombre: "Biblioteca Niños",
        categoria: "Almacenamiento",
        tipo: "Mobiliario Hogar",
        precio: "$3.800.000",
        color: "Blanco",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 6,
        nombre: "Mesa Harmony Nogal 180x90cm",
        categoria: "Comedor",
        tipo: "Mobiliario Hogar",
        precio: "$7.000.000",
        color: "Makadamia",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 7,
        nombre: "Mesa South Beach 180x90cm",
        categoria: "Comedor",
        tipo: "Mobiliario Hogar",
        precio: "$5.000.000",
        color: "Gris",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 8,
        nombre: "Mesa Cesaro 200x100cm",
        categoria: "Mueble de Sala",
        tipo: "Mobiliario Hogar",
        precio: "$10.000.000",
        color: "Abedul",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 9,
        nombre: "Mesa Cesaro 200x100cm",
        categoria: "Mueble de Sala",
        tipo: "Mobiliario Hogar",
        precio: "$10.000.000",
        color: "Abedul",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 10,
        nombre: "Mesa Bora Bora 80x80",
        categoria: "Mueble de Sala",
        tipo: "Mobiliario Hogar",
        precio: "$1.300.000",
        color: "Negra",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 11,
        nombre: "Mesa Brooklyn Nature 80x160cm",
        categoria: "Mueble de Sala",
        tipo: "Mobiliario Hogar",
        precio: "$6.300.000",
        color: "Madera",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 12,
        nombre: "Silla Reposabrazos Costa",
        categoria: "Mueble de Sala",
        tipo: "Mobiliario Hogar",
        precio: "2.500.000",
        color: "Negro",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 13,
        nombre: "Mesa polar latón",
        categoria: "Mueble de Sala",
        tipo: "Mobiliario Hogar",
        precio: "2.000.000",
        color: "Mate",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
      },
      {
        id: 14,
        nombre: "Silla Butterfly",
        categoria: "Mueble de Sala",
        tipo: "Mobiliario Hogar",
        precio: "3.2000.000",
        color: "Marron",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 15,
        nombre: "Mesilla Luxury",
        categoria: "Mueble de cuarto",
        precio: "8.0000.000",
        color: "Marron",
        medida: "49x50cm",
        peso: "17.58kg",
        descripcion: "Esta mesillamoderna y sofisticada está compuesta por una estructura de madera comprimida lacada en negro y paneles de espejo. Su silueta minimalista está resaltada por unas asas de cristal que evocan los diamantes y contrastan con sus ángulos rectos.",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
      },
      {
        id: 16,
        nombre: "Mesa Office Symphony",
        categoria: "Administrativo",
        precio: "13.8000.000",
        color: "Madera",
        medida: "160x70cm",
        peso: "64.5kg",
        descripcion: "Esta mesa nos permite tener un entorno administrativo sin necesidad de salir de nuestro hogar, esta 100% equipada para las necesidades laborales.",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 17,
        nombre: "Silla Oficina Giratoria",
        categoria: "Administrativo",
        precio: "2.3000.000",
        color: "Beige",
        medida: "57x105cm",
        peso: "12.5kg",
        descripcion: "Esta silla de oficina ajustable es un clásico con sus ángulos rectos y su color polivalente. Te dará un ambiente serio para trabajar.",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 18,
        nombre: "Silla Oficina Giratoria",
        categoria: "Administrativo",
        precio: "2.3000.000",
        color: "Beige",
        medida: "57x105cm",
        peso: "12.5kg",
        descripcion: "Esta silla de oficina ajustable es un clásico con sus ángulos rectos y su color polivalente. Te dará un ambiente serio para trabajar.",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        },
      {
        id: 19,
        nombre: "Estanteria Loft",
        categoria: "Administrativo",
        precio: "4.8000.000",
        color: "Oro",
        medida: "115x195cm",
        peso: "41.3kg",
        descripcion: "Los estantes abiertos son compañeros de decoración ideales ayudan a mantener las cosas ordenadas, lucen ligeras y gracias al gran espacio de almacenamiento en los estantes, ofrecen mucho espacio para decoraciones, cajas, cestas o jarrones o en el estilo clásico, para libros.",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
      },
      {
        id: 20,
        nombre: "Sofa Cubetto 3 Puestos",
        categoria: "Mueble de Sala",
        precio: "20.0000.000",
        color: "Crema",
        medida: "220x67cm",
        peso: "74kg",
        descripcion: "El sofá Cubetto 3 pl crema 220cm es un elemento imprescindible para cualquier hogar contemporáneo. Este sofá de estilo moderno y escandinavo, fabricado con madera de abeto y tapizado con material sintético de color beige, ofrece una combinación perfecta de comodidad y estilo.",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
      },
      {
        id: 21,
        nombre: "Exterior Sofa Set Holiday",
        categoria: "Mueble de Sala",
        precio: "14.3000.000",
        color: "Gris",
        medida: "242x63cm",
        peso: "50kg",
        descripcion: "¿Qué podría ser más hermoso que mover la vida afuera en los primeros rayos del sol? Es aún mejor si todos pueden encontrar un lugar cómodo para sentarse o relajarse juntos, como en el grupo de asientos de la esquina navideña, que también viene con una mesa.",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
      },
    ],
  }
  